// Korean vocabulary organized by difficulty levels
const koreanVocabulary = {
  level1: [
    { korean: '안녕하세요', english: 'Hello', pronunciation: 'annyeonghaseyo' },
    { korean: '감사합니다', english: 'Thank you', pronunciation: 'gamsahamnida' },
    { korean: '네', english: 'Yes', pronunciation: 'ne' },
    { korean: '아니요', english: 'No', pronunciation: 'aniyo' },
    { korean: '사랑', english: 'Love', pronunciation: 'sarang' },
    { korean: '물', english: 'Water', pronunciation: 'mul' },
    { korean: '밥', english: 'Rice/Food', pronunciation: 'bap' },
    { korean: '친구', english: 'Friend', pronunciation: 'chingu' },
    { korean: '학교', english: 'School', pronunciation: 'hakgyo' },
    { korean: '집', english: 'House/Home', pronunciation: 'jip' },
    { korean: '가족', english: 'Family', pronunciation: 'gajok' },
    { korean: '엄마', english: 'Mom', pronunciation: 'eomma' },
    { korean: '아빠', english: 'Dad', pronunciation: 'appa' },
    { korean: '책', english: 'Book', pronunciation: 'chaek' },
    { korean: '이름', english: 'Name', pronunciation: 'ireum' },
    { korean: '시간', english: 'Time', pronunciation: 'sigan' },
    { korean: '하나', english: 'One', pronunciation: 'hana' },
    { korean: '둘', english: 'Two', pronunciation: 'dul' },
    { korean: '셋', english: 'Three', pronunciation: 'set' },
    { korean: '사람', english: 'Person', pronunciation: 'saram' },
  ],
  level2: [
    { korean: '여행', english: 'Travel', pronunciation: 'yeohaeng' },
    { korean: '음식', english: 'Food', pronunciation: 'eumsik' },
    { korean: '날씨', english: 'Weather', pronunciation: 'nalssi' },
    { korean: '기분', english: 'Mood/Feeling', pronunciation: 'gibun' },
    { korean: '생각', english: 'Thought/Thinking', pronunciation: 'saenggak' },
    { korean: '시작', english: 'Start/Beginning', pronunciation: 'sijak' },
    { korean: '끝', english: 'End', pronunciation: 'kkeut' },
    { korean: '문제', english: 'Problem', pronunciation: 'munje' },
    { korean: '대답', english: 'Answer', pronunciation: 'daedap' },
    { korean: '질문', english: 'Question', pronunciation: 'jilmun' },
    { korean: '이야기', english: 'Story/Talk', pronunciation: 'iyagi' },
    { korean: '약속', english: 'Promise/Appointment', pronunciation: 'yaksok' },
    { korean: '선물', english: 'Gift', pronunciation: 'seonmul' },
    { korean: '생일', english: 'Birthday', pronunciation: 'saeng-il' },
    { korean: '계획', english: 'Plan', pronunciation: 'gyehoek' },
    { korean: '경험', english: 'Experience', pronunciation: 'gyeongheom' },
    { korean: '연습', english: 'Practice', pronunciation: 'yeonseup' },
    { korean: '회사', english: 'Company', pronunciation: 'hoesa' },
    { korean: '도시', english: 'City', pronunciation: 'dosi' },
    { korean: '나라', english: 'Country', pronunciation: 'nara' },
  ],
  level3: [
    { korean: '환경', english: 'Environment', pronunciation: 'hwangyeong' },
    { korean: '문화', english: 'Culture', pronunciation: 'munhwa' },
    { korean: '경제', english: 'Economy', pronunciation: 'gyeongje' },
    { korean: '정치', english: 'Politics', pronunciation: 'jeongchi' },
    { korean: '기술', english: 'Technology/Skill', pronunciation: 'gisul' },
    { korean: '발전', english: 'Development/Progress', pronunciation: 'baljeon' },
    { korean: '변화', english: 'Change', pronunciation: 'byeonhwa' },
    { korean: '영향', english: 'Influence', pronunciation: 'yeonghyang' },
    { korean: '관계', english: 'Relationship', pronunciation: 'gwangye' },
    { korean: '의미', english: 'Meaning', pronunciation: 'uimi' },
    { korean: '중요', english: 'Important', pronunciation: 'jungyо' },
    { korean: '필요', english: 'Necessary', pronunciation: 'piryo' },
    { korean: '가능', english: 'Possible', pronunciation: 'ganeung' },
    { korean: '특별', english: 'Special', pronunciation: 'teukbyeol' },
    { korean: '자연', english: 'Nature', pronunciation: 'jayeon' },
    { korean: '역사', english: 'History', pronunciation: 'yeoksa' },
    { korean: '미래', english: 'Future', pronunciation: 'mirae' },
    { korean: '현재', english: 'Present', pronunciation: 'hyeonjae' },
    { korean: '과거', english: 'Past', pronunciation: 'gwageo' },
    { korean: '사회', english: 'Society', pronunciation: 'sahoe' },
  ],
};

export default koreanVocabulary;
